#!/usr/bin/env python3
"""Generate shaders/dxhr/table.csv from Luma's DXHR HLSL filenames.

Luma names its replacement shaders as:
    <DescriptiveName>_0x<HASH>[[_0x<HASH>]...].<profile>.hlsl
e.g.
    MLAAMask1Gen_0x6B0219A1.ps_5_0.hlsl
    BloomBlur_0x81EC9518_0xF3997851.ps_5_0.hlsl   (one file, two original hashes)

The 0xHASH is ReShade's compute_crc32 over the original game shader's DXBC
bytecode (see src/ShaderHash.h). A single replacement file can cover several
original hashes; we emit one CSV row per hash.

Files without a 0x hash (Luma_DXHR_XeGTAO, Luma_SMAA_Linearize,
Luma_ModulateLighting) are *injected* passes scheduled by name, not hash
replacements. They belong to Phase 3 (injected passes) and are skipped here.

Output CSV columns: hash,name,profile,cso
  hash    : 0x%08X  (ReShade shader_hash)
  name    : descriptive label (filename stem minus hash/profile)
  profile : ps_5_0 / cs_5_0 / vs_5_0
  cso     : compiled/<stem>.cso  (relative to shaders/dxhr/)

The .cso files are produced by the offline compile step (tools/compile_shaders
in CI); the table can be generated before they exist.
"""
import re, sys, csv, pathlib

HASH_RE = re.compile(r'0x([0-9A-Fa-f]{8})')
PROFILE_RE = re.compile(r'\.(ps|cs|vs)_(\d_\d)\.hlsl$')

def main():
    src = pathlib.Path('shaders/dxhr')
    out = pathlib.Path('shaders/dxhr/table.csv')
    if not src.is_dir():
        print(f'error: {src} not found (run from repo root)', file=sys.stderr)
        return 1

    rows = []
    skipped = []
    for hlsl in sorted(src.glob('*.hlsl')):
        stem = hlsl.stem  # e.g. MLAAMask1Gen_0x6B0219A1.ps_5_0
        hashes = HASH_RE.findall(stem)
        if not hashes:
            skipped.append(hlsl.name)
            continue
        m = PROFILE_RE.search(hlsl.name)
        if not m:
            skipped.append(hlsl.name)
            continue
        profile = f'{m.group(1)}_{m.group(2)}'
        # Descriptive name = stem with all _0xHASH segments removed and the
        # trailing .profile removed.
        name = HASH_RE.sub('', stem)
        name = re.sub(r'\.(ps|cs|vs)_\d_\d$', '', name)
        name = name.rstrip('_')
        # cso path uses the full filename (minus .hlsl) so each row points at
        # the blob compiled from that specific .hlsl file.
        cso = f'compiled/{hlsl.name[:-5]}.cso'
        for h in hashes:
            rows.append((f'0x{h.upper()}', name, profile, cso))

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open('w', newline='') as f:
        # Comment line written raw (not via csv.writer) so the C++ parser's
        # leading-# skip works; csv.writer would quote it because of commas.
        f.write('# hash,name,profile,cso  — generated by tools/gen_shader_table.py\n')
        w = csv.writer(f)
        for r in rows:
            w.writerow(r)

    print(f'wrote {out}: {len(rows)} rows from {len(list(src.glob("*.hlsl")))} files')
    if skipped:
        print(f'skipped (no hash / injected-pass): {", ".join(skipped)}')
    return 0

if __name__ == '__main__':
    sys.exit(main())
